apiVersion: apps/v1
kind: ReplicaSet
metadata:
      name: nginx
      labels:
        tier: nginx
spec:
   
      replicas: 3
      selector:
        matchLabels:
          tier: nginx
      template:
        metadata:
          labels:
            tier: nginx
        spec:
          containers:
          - name: backend
            image: nginx